extends:
  - 'yoast-base'
  - 'plugin:@typescript-eslint/recommended'

plugins:
  - '@typescript-eslint/eslint-plugin'

parser: '@typescript-eslint/parser'
parserOptions:
  project: 'tsconfig.json'
  ecmaVersion: 2018
  sourceType: 'module'

env:
  node: true
  jest: true

# http://eslint.org/docs/rules/
rules:
  'new-cap': 0
  'no-prototype-builtins': 0
  'no-dupe-class-members': 0
  'no-unused-vars': 0
  '@typescript-eslint/no-unused-vars': 2
  'ident': 0
  '@typescript-eslint/indent': [ 2, 'tab', { 'SwitchCase': 1 }]
  '@typescript-eslint/interface-name-prefix': 0
  '@typescript-eslint/explicit-function-return-type': 0
  '@typescript-eslint/explicit-module-boundary-types': 0
  '@typescript-eslint/no-explicit-any': 0
  'space-before-function-paren': [ 2, { 'anonymous': 'never', 'named': 'never', 'asyncArrow': 'always' }]
